name: lint-test-build  # nama workflow github action

on: [push] # kondisi trigger workflow, adalah saat ada push di branch

jobs:

# job pertama
  lint-dockerfile:  
    runs-on: ubuntu-latest  # job di run pada ubuntu
    steps:
      - name: Checkout code  # mengambil code dari repository
        uses: actions/checkout@v4  # menggunakan action version 4
      - name: Lint Dockerfile  
        run: |
          docker run --rm -i hadolint/hadolint < Dockerfile  

# job kedua
  test-app:  # Name of the second job
    runs-on: ubuntu-latest  # job di run pada ubuntu
    needs: lint-dockerfile  # dependensi atas job yang pertama
    steps:
      - name: Checkout code  
        uses: actions/checkout@v4  
      - name: Set up Go  
        uses: actions/setup-go@v4  
        with:
          go-version: '1.21.0'  # menentukan versi Go
      - name: Run Unit Tests  
        run: go test -v -short --count=1 $(go list ./...)  # melakukan unit testing

# job ketiga
  build-app-karsajobs:  
    runs-on: ubuntu-latest  # job di run pada ubuntu
    needs: test-app  # dependensi atas job yang kedua
    steps:
      - name: Checkout code  
        uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3  
      - name: Login to GitHub Container Registry  
        uses: docker/login-action@v3  
        with:
          registry: ghcr.io  # menentukan GitHub Container Registry
          username: ${{github.actor}}
          password: ${{secrets.GHCR_TOKEN}}
      - name: Build and push Docker image  
        run: |
          docker build -t ghcr.io/${{github.actor}}/karsajobs:latest .  
          docker push ghcr.io/${{github.actor}}/karsajobs:latest  