name: lint-test-build 
on:
  push:
    branches:
      - karsajobs-ui  

jobs:
  lint-dockerfile:  
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code  
        uses: actions/checkout@v4 
      - name: Lint Dockerfile
        run: |
          docker run --rm -i hadolint/hadolint < Dockerfile  

  build-app-karsajobs-ui:  
    runs-on: ubuntu-latest  
    needs: lint-dockerfile 

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry 
        uses: docker/login-action@v3
        with:
          registry: ghcr.io 
          username: ${{github.actor}}
          password: ${{secrets.GHCR_TOKEN}}
      - name: Build and push Docker image 
        run: |
          docker build -t ghcr.io/${{github.actor}}/karsajobs-ui:latest .  
          docker push ghcr.io/${{github.actor}}/karsajobs-ui:latest
